ARDUINO_LIBS  := Adafruit_MAX31855 PID_Controller Adafruit_GFX Adafruit_LED_Backpack Wire
BOARD_TAG     := uno
ARDUINO_PORT  := /dev/ttyUSB0
USER_LIB_PATH := $(realpath $(HOME)/sketchbook/libraries/)
CXXFLAGS      += -std=gnu++11
CFLAGS        += -std=gnu++11


include /usr/share/arduino/Arduino.mk
